import { IFriendNode } from '@/entities/Friend/types/friend';
import { mockAvatar } from '@/shared/const/mockAvatar';

export const mockFriendsNode: IFriendNode[] = [
  {
    right: {
      right: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username9',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      left: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username10',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      avatar: mockAvatar,
      username: '@username1',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    left: {
      right: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username11',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      left: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username12',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      avatar: mockAvatar,
      username: '@username2',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    avatar: mockAvatar,
    username: '@username',
    friendsCount: 2,
    lgCoinsAmount: 8555,
  },
  {
    right: {
      right: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username13',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      left: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username14',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      avatar: mockAvatar,
      username: '@username3',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    left: {
      right: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username7',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      left: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username8',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      avatar: mockAvatar,
      username: '@username4',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    avatar: mockAvatar,
    username: '@longusernameusername',
    friendsCount: 2,
    lgCoinsAmount: 8555,
  }
];
export const mockFriendsNode2: IFriendNode[] = [
  {
    right: {
      right: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username9',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      left: null,
      avatar: mockAvatar,
      username: '@username1',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    left: {
      right: null,
      left: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username12',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      avatar: mockAvatar,
      username: '@username2',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    avatar: mockAvatar,
    username: '@username',
    friendsCount: 2,
    lgCoinsAmount: 8555,
  },
  {
    right: {
      right: null,
      left: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username14',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      avatar: mockAvatar,
      username: '@username3',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    left: {
      right: {
        right: null,
        left: null,
        avatar: mockAvatar,
        username: '@username7',
        friendsCount: 2,
        lgCoinsAmount: 8555,
      },
      left: null,
      avatar: mockAvatar,
      username: '@username4',
      friendsCount: 2,
      lgCoinsAmount: 8555,
    },
    avatar: mockAvatar,
    username: '@longusernameusername',
    friendsCount: 2,
    lgCoinsAmount: 8555,
  }
];
